
DROP DATABASE IF EXISTS `school_db`;
CREATE DATABASE IF NOT EXISTS  `school_db`;

USE `school_db`;

DROP TABLE IF EXISTS `school_db`.`schoolTable`;

CREATE TABLE IF NOT EXISTS `school_db`.`schoolTable` (
    `SCHOOL_YEAR` VARCHAR(12),
    `PUBLIC_OR_INDEPENDENT` VARCHAR(30),
    `DISTRICT_NUMBER` VARCHAR(5),
    `DISTRICT_LONG_NAME_THIS_ENROL` VARCHAR(50),
    `SCHOOL_NUMBER` VARCHAR(10),
    `SCHOOL_NAME` VARCHAR(50),
    `SCHOOL_FACILITY_TYPE` VARCHAR(50),
    `SCHOOL_PHYSICAL_ADDRESS` VARCHAR(50),
    `SCHOOL_CITY` VARCHAR(20),
    `SCHOOL_PROVINCE` VARCHAR(50),
    `SCHOOL_POSTAL_CODE` VARCHAR(50),
    `SCHOOL_PHONE_NUMBER` VARCHAR(20),
    `SCHOOL_FAX_NUMBER` VARCHAR(20),
    `SCHOOL_LATITUDE` DECIMAL(10,7),
    `SCHOOL_LONGITUDE` DECIMAL(10,7),
    `ORGANIZATION_EDUCATION_LEVEL` VARCHAR(20),
    `GRADE_STRING` VARCHAR(10),
    `HAS_ELEMENTARY_GRADES_FLAG` TINYINT(1),
    `HAS_SECONDARY_GRADES_FLAG` TINYINT(1),
    INDEX(SCHOOL_NUMBER(5))
)ENGINE = MyISAM;

LOAD DATA LOCAL INFILE './SchoolLocations_Hist_Custom.csv' INTO TABLE `schoolTable` FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n' ignore 1 lines;
